#!/bin/bash
GIT_DIR=~/git


# DISCLAMERS:
#   - currently tested for OSX
#   - will fail if there are changes in the repo
main() {
  local folder_name=$1

  for repo_folder in $(ls $GIT_DIR/$folder_name); do
    repo_name=$(basename $repo_folder)
    echo "Updating $repo_name..."
    cd $repo_folder
    repo_main_branch=`git symbolic-ref refs/remotes/origin/HEAD --short | awk -F '/' {'print $2'}`
    # change this to find main branch
    # checkout and update
    git checkout $repo_main_branch
    git pull
  done
}

main
